spring:
  application:
    name: library
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/mydb
    username: user
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
